<?php 

/*
define('APP_ROOT', "__APPLICATION_APP_ROOT_DIR__");
define('APP_SRC', "__APPLICATION_FULL_DOMAIN_NAME__");
define('APP_NAME', "__APPLICATION_NAME__");
define('APP_AUTHOR', "__APPLICATION_AUTHOR__");
*/
